# Don't do any CI builds - this pipeline is purely for PR's
trigger:
  branches:
    exclude:
    -  '*'
pr:
- master

# GitHub status API endpoint, update with your Github repo details
variables:
- name: GitHubStatusApiUrl
  value: https://api.github.com/repos/Penterfield/Iac_Terra_Security
  
pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    mkdir CheckovReport
    docker pull bridgecrew/checkov
    docker run --volume $(System.DefaultWorkingDirectory):/tf bridgecrew/checkov --directory /tf -o cli
    exitCode=$?
    [[ $exitCode = 0 ]] && state="success" || state="failure"
    echo "##vso[task.setvariable variable=CheckovState;]$state"
    exit $exitCode
  continueOnError: false
  displayName: 'Checkov Scan'

# PROVIDE BUILD FEEDBACK
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: CheckovResults

# PROVIDE PR FEEDBACK
- template: templates/azure-pipelines-github-feedback-template.yml  # Template reference
  parameters:
    state: $(CheckovState)