# Don't do any CI builds - this pipeline is purely for PR's
trigger:
  branches:
    exclude:
    -  '*'
pr:
- master

variables:
- name: GitHubStatusApiUrl
  value: https://api.github.com/repos/Penterfield/Iac_Terra_Security

pool:
  vmImage: 'ubuntu-latest'
  
steps:

# configure the version of python to use 
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Install Python 3.8'

# install python packages for checkov
- script: pip install checkov
  displayName: 'Install the Checkov CLI'
  
# run checkov against files in working directory
- bash: | 
    checkov -d $(System.DefaultWorkingDirectory) 
    checkov -d $(System.DefaultWorkingDirectory) --output json > $(Build.ArtifactStagingDirectory)/Checkov-Report.json
#     exitCode=$?
#     [[ $exitCode = 0 ]] && state="success" || state="failure"
#     echo "##vso[task.setvariable variable=CheckovState;]$state"
#     exit $exitCode
  displayName: 'Checkov Scan'
  continueOnError: true

# PROVIDE BUILD FEEDBACK
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: CheckovResults

# PROVIDE PR FEEDBACK
- template: azure-pipelines-github-feedback-template.yml  # Template reference
  parameters:
    state: $(CheckovState)
    
