trigger:
  - master
  
pool:
  vmImage: 'ubuntu-latest'

steps:

 - script: |
     mkdir CheckovReport
     docker pull bridgecrew/checkov
     docker run --volume $(System.DefaultWorkingDirectory):/tf bridgecrew/checkov --directory /tf -o cli
     exitCode=$?
     [[ $exitCode = 0 ]] && state="success" || state="failure"
     echo "##vso[task.setvariable variable=CheckovState;]$state"
     exit $exitCode
   continueOnError: true
   displayName: 'Checkov Console output'